version: '3'
services:
  twilio-flex-demo:
    build:
      context: ../flex-ui-sample
    environment:
      REACT_APP_ID: ''
      REACT_APP_SECRET: ''
    ports:
      - "8080:8080"
    command: /bin/bash -c "/usr/bin/envsubst < /src/app/.env.template > /src/app/.env && ./env.sh && cp env-config.js /var/www/public/ &&exec nginx -g 'daemon off;'"
